name: CI Process
on: [ push ]

jobs:
  phpstan:
    runs-on: ubuntu-20.04
    name: "PHPStan"
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - name: "Switch default PHP Version to 8.1"
        run: sudo update-alternatives --set php /usr/bin/php8.1

      - name: "Install Composer dependencies"
        run: composer install

      - name: "PHPStan"
        run: vendor/bin/phpstan

  composer_normalize:
    runs-on: ubuntu-20.04
    name: "composer normalize"
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - name: "Switch default PHP Version to 8.1"
        run: sudo update-alternatives --set php /usr/bin/php8.1

      - name: "Install Composer dependencies"
        run: composer install

      - name: "Normalize"
        run: composer normalize

  phpunit:
    strategy:
      matrix:
        version: [ /usr/bin/php8.1, /usr/bin/php8.2 ]
    runs-on: ubuntu-20.04
    name: "PHPUnit with ${{ matrix.version }}"
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: "Switch default PHP to: ${{ matrix.version }}"
        run: sudo update-alternatives --set php ${{ matrix.version }}

      - name: "Print PHP version"
        run: php --version

      - name: "Print PHPUnit --version"
        run: tools/phpunit --version

      - name: "PHPUnit"
        run: tools/phpunit